import PokeAPIDatabase
import StructuredQueries
import StructuredQueriesSQLite
import Testing

/// To check the data imports correctly, we read all records for all tables
@Test func testRuntimeCheckSchemas() throws {
    let database = StructuredQueriesSQLite.Database.pokeAPI
    let _ = try database.execute(PokeAPIAbility.all)
    let _ = try database.execute(PokeAPIBerry.all)
    let _ = try database.execute(PokeAPICharacteristic.all)
    let _ = try database.execute(PokeAPIEggGroup.all)
    let _ = try database.execute(PokeAPIEncounter.all)
    let _ = try database.execute(PokeAPIEncounterMethod.all)
    let _ = try database.execute(PokeAPIEncounterSlot.all)
    let _ = try database.execute(PokeAPIEvolutionChain.all)
    let _ = try database.execute(PokeAPIEvolutionTrigger.all)
    let _ = try database.execute(PokeAPIExperience.all)
    let _ = try database.execute(PokeAPIGeneration.all)
    let _ = try database.execute(PokeAPIGrowthRate.all)
    let _ = try database.execute(PokeAPIItem.all)
    let _ = try database.execute(PokeAPIItemCategory.all)
    let _ = try database.execute(PokeAPILocation.all)
    let _ = try database.execute(PokeAPILocationArea.all)
    let _ = try database.execute(PokeAPIMachine.all)
    let _ = try database.execute(PokeAPIMove.all)
    let _ = try database.execute(PokeAPIMoveDamageClass.all)
    let _ = try database.execute(PokeAPIMoveEffect.all)
    let _ = try database.execute(PokeAPIMoveTarget.all)
    let _ = try database.execute(PokeAPINature.all)
    let _ = try database.execute(PokeAPIPokedex.all)
    let _ = try database.execute(PokeAPIPokemon.all)
    let _ = try database.execute(PokeAPIPokemonAbility.all)
    let _ = try database.execute(PokeAPIPokemonColor.all)
    let _ = try database.execute(PokeAPIPokemonDexNumber.all)
    let _ = try database.execute(PokeAPIPokemonEggGroup.all)
    let _ = try database.execute(PokeAPIPokemonEvolution.all)
    let _ = try database.execute(PokeAPIPokemonHabitat.all)
    let _ = try database.execute(PokeAPIPokemonItem.all)
    let _ = try database.execute(PokeAPIPokemonMove.all)
    let _ = try database.execute(PokeAPIPokemonShape.all)
    let _ = try database.execute(PokeAPIPokemonSpecies.all)
    let _ = try database.execute(PokeAPIPokemonStat.all)
    let _ = try database.execute(PokeAPIPokemonType.all)
    let _ = try database.execute(PokeAPIRegion.all)
    let _ = try database.execute(PokeAPIStat.all)
    let _ = try database.execute(PokeAPIType.all)
    let _ = try database.execute(PokeAPITypeEfficacy.all)
    let _ = try database.execute(PokeAPIVersion.all)
    let _ = try database.execute(PokeAPIVersionGroup.all)
}
